name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  id-token: write

jobs:
  publish-jsr:
    name: Publish to JSR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2

      - run: deno publish

  publish-npm:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org

      - uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Transform and Publish
        run: |
          deno -A _transform.ts
          cd dist
          npm publish --access public
        env:
          __TYPE_MAP: 1
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  create-release:
    name: Create Release
    needs: publish-npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          generate_release_notes: true
